---
engines:
  csslint:
    enabled: true
  editorconfig:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
#      - ruby
      - javascript
#      - python
#      - php
#  eslint:
#    enabled: true
#    channel: "eslint-8"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.json"
  - "**.js"
  - "**.njk"
