version: "2"
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  editorconfig:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-9
  fixme:
    enabled: true
  markdownlint:
    enabled: true
