name: "Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    name: 'MarkdownLint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Validate Markdown Sources
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
  eslint:
    runs-on: ubuntu-latest
    name: 'ESLint'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install
      - name: Validate JS Sources
        run: npm run validate:js
  stylelint:
    runs-on: ubuntu-latest
    name: 'Stylelint'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install
      - name: Validate CSS Sources
        run: npm run validate:css
  unit:
    runs-on: ubuntu-latest
    name: 'Unit Tests'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install
      - name: Execute Unit Tests
        run: npm run test
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
